title: "peterstrahle.dev blog"
description: "I will write about technical art and other problems that can appear when working in game productions. With focus on the problem solving. If you have questions about the blog you can reach me on [LinkedIn](https://www.linkedin.com/in/peterstrahle)"

theme: minima
show_excerpts: true
excerpt_separator: "<!--more-->"
markdown: kramdown

sass:
  style: compressed
  
include:
  - assets

minima:
  include_head: true

